[project]
name = "langchain-app"
version = "0.1.0"
description = "LangChain experiments and applications"
readme = "README.md"
authors = [
    { name = "Anik Chowdhury", email = "chowdhuryanik027@gmail.com" }
]
requires-python = ">=3.13"

dependencies = [
    "langchain",
    "langchain-core",
    "langchain-openai",
    "openai",
    "langchain-anthropic",
    "langchain-google-genai",
    "google-generativeai",
    "langchain-huggingface",
    "transformers",
    "huggingface-hub",
    "python-dotenv",
    "numpy",
    "scikit-learn",
    "typing-extensions",
    "pydantic",
    "email-validator",
    "langchain-groq",
    "langchain-classic",
    "langchain-community",
    "wikipedia",
    "langchain-chroma",
]

[project.scripts]
langchain = "langchain:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
